messages:
  vote-command:
  - '&4Voting sites:'
  
update-topvotes-minutes: 10

rewards:
  default:
    active: true
    permission: vote.receive
    actions: 
    - '[message] &7Thanks for voting!'
    - '[broadcast] &8%player% &6voted, what a legend!'
    - '[title] &9Test'
    - '[subtitle] &8No tst'
    - '[actionbarmessage] &8%player% &6voted, what a legend!'
    - '[consolecommand] gamemode 0 %player%'    
  all:
    active: true
    permission: vote.receive
    actions: 
    - '[message] &7Thanks for voting!'
    - '[broadcast] &8%player% &6voted, what a legend!'
    - '[consolecommand] op %player%'